import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState } from "react";

export default function Home() {
  const [inputs, setInputs] = useState({
    name: "",
    surname: "",
    email: "",
    dob: "",
    phone: "",
    timestamp: "",
  });
  const [mask, updateMask] = useState(0);
  const [code, updateCode] = useState("");

  const handleSubmit = (e) => {
    e?.preventDefault();
    console.log(mask);
    const payload = { data: { ...inputs, timestamp: +new Date() }, mask };
    axios.post("http://localhost:3000/api/scan", payload).then((response) => {
      console.log(response);
      updateCode(response.data);
    });
  };

  const handleInputChange = (event) => {
    event.persist();
    setInputs((inputs) => ({
      ...inputs,
      [event.target.name]: event.target.value,
    }));
  };

  const newPattern = (e) => {
    e?.preventDefault();
    updateMask(((mask + 1) % 8));
    handleSubmit();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleSubmit} className="qr-form">
          <label>
            Name:
            <input
              type="text"
              name="name"
              value={inputs.name}
              onChange={handleInputChange}
              required
            />
          </label>
          <label>
            Last Name:
            <input
              type="text"
              name="surname"
              value={inputs.surname}
              onChange={handleInputChange}
              required
            />
          </label>
          <label>
            Email:
            <input
              name="email"
              type="email"
              value={inputs.email}
              onChange={handleInputChange}
              required
            />
          </label>
          <label>
            Phone:
            <input
              name="phone"
              type="tel"
              value={inputs.phone}
              onChange={handleInputChange}
              required
            />
          </label>
          <label>
            Date of birth:
            <input
              name="dob"
              type="date"
              value={inputs.dob}
              onChange={handleInputChange}
              required
            />
          </label>
          <input type="submit" value="Get QR" />
        </form>
        <button onClick={newPattern}>New pattern</button>
        <img src={code} alt="" />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
